module.exports = [
    {
      key:1,
      category:'KidsWear', 
      icon:"./Assets/Images/Icons/Kidswear.png"
    },
    {
      key:2,
      category:'Cinema', 
      icon:"./Assets/Images/Icons/cinema.png"
    },
    {
      key:3,
      category:'Clothing & Footwear', 
      icon:"./Assets/Images/Icons/Clothes.png"
    },
    {
      key:4,
      category:'Electronics', 
      icon:"./Assets/Images/Icons/Electronics.png"
    },
    {
      key:5,
      category:'KidsWear', 
      icon:"./Assets/Images/Icons/Kidswear.png"
    },
    {
      key:6,
      category:'Cinema', 
      icon:"./Assets/Images/Icons/cinema.png"
    },
    {
      key:7,
      category:'Clothing & Footwear', 
      icon:"./Assets/Images/Icons/Clothes.png"
    },
    {
      key:8,
      category:'Electronics', 
      icon:"./Assets/Images/Icons/Electronics.png"
    },
    {
      key:9,
      category:'KidsWear', 
      icon:"./Assets/Images/Icons/Kidswear.png"
    },
    {
      key:10,
      category:'Cinema', 
      icon:"./Assets/Images/Icons/cinema.png"
    },
    {
      key:11,
      category:'Clothing & Footwear', 
      icon:"./Assets/Images/Icons/Clothes.png"
    },
    {
      key:12,
      category:'Electronics', 
      icon:"./Assets/Images/Icons/Electronics.png"
    },
    {
      key:13,
      category:'Electronics', 
      icon:"./Assets/Images/Icons/Electronics.png"
    },
    {
      key:14,
      category:'KidsWear', 
      icon:"./Assets/Images/Icons/Kidswear.png"
    },
    {
      key:15,
      category:'Cinema', 
      icon:"./Assets/Images/Icons/cinema.png"
    },
    {
      key:16,
      category:'Clothing & Footwear', 
      icon:"./Assets/Images/Icons/Clothes.png"
    },
    {
      key:17,
      category:'Electronics', 
      icon:"./Assets/Images/Icons/Electronics.png"
    },
  ];