module.exports=[
    {
        key:1,
        name:"Delhi",
        img:"./Assets/Images/Cities/Delhi.jpg"
    },
    {
      key:2,
        name:"Mumbai",
        img:"./Assets/Images/Cities/Mumbai.jpg"
    },
    {
      key:3, 
      name:"Banglore",
      img:"./Assets/Images/Cities/Banglore.jpg"
    },
    {
      key:4,
      name:"Goa",
      img:"./Assets/Images/Cities/Goa.jpg"
    },
    {
      key:5,
      name:"Hydrabad",
      img:"./Assets/Images/Cities/Hydrabad.jpg"
    },
    {
      key:6,
      name:"Surat",
      img:"./Assets/Images/Cities/Surat.jpg"
    }
  ];