module.exports = [
    {
        key:1,
        name: "Yellow Door cafe",
        img:"./Assets/Images/Shop.jpg",
        city: "New Delhi",
        rating : 4.6,
        reviews : 21,
        contact : ["+(91)-9650560949", "(011)-9810962664"],
        email: "yellowdoorcafe@gmail.com",
        about:"Home Centre is a perfect destination to help you decorate your dream abode. Walk into our stores today to discover tasteful furniture, home ware and soft furnishing products that truly represents style, comfort and individuality. In the year 2005, Dubai based retail conglomerate Landmark Group launched its first specialized, stand-alone home improvement store – Home Centre. Home Centre is a one stop destination for furniture, homeware and soft furnishing that truly represents style, comfort and individuality. The stores use unique ‘concept’ rooms as the display model, to give consumers a practical idea of how each piece of furniture would look in a particular room. There are currently 15 Home Centre stores across the country in key cities including Gurgaon, Bangalore, Mumbai, Noida, Pune, Chennai, Delhi, Coimbatore, Mangalore and Hyderabad. Most of the stores are situated at high streets Malls and spread over a sprawling area of approx. 20,000 - 40,000 sq. ft. Home Centre features a host of products sourced from across the globe including furniture, home décor and soft furnishing, offering consumers a choice of categorized and coordinated shopping. The store’s USP is to provide a ‘touch and feel’ experience for shoppers and allows them to envisage how the products will lend a sense character and uniqueness to their home.        ",
        productList:"Furniture, homeware, soft furnishing, crockery, cutlery & kitchen utensils, bath products, wicker products, CD & magazine racks, towels, bed spreads, shower curtains, laundry hampers, utility brushes, iron boards, cutlery, glassware, lamps in sleek and tall patterns, artificial flowers, ceramic vases, crystal ware etc.",
        type : "Restaurant",
        location:"SG-23, Galleria Market, DLF City Phase IV, Gurugram, Haryana,122009",
        availability:"Open all day"
    },
    {
        key:2,
        name: "Yellow Door cafe",
        img:"./Assets/Images/Shop.jpg",
        city: "New Delhi",
        rating : 4.6,
        reviews : 21,
        contact : ["+(91)-9650560949", "(011)-9810962664"],
        email: "yellowdoorcafe@gmail.com",
        about:"Home Centre is a perfect destination to help you decorate your dream abode. Walk into our stores today to discover tasteful furniture, home ware and soft furnishing products that truly represents style, comfort and individuality. In the year 2005, Dubai based retail conglomerate Landmark Group launched its first specialized, stand-alone home improvement store – Home Centre. Home Centre is a one stop destination for furniture, homeware and soft furnishing that truly represents style, comfort and individuality. The stores use unique ‘concept’ rooms as the display model, to give consumers a practical idea of how each piece of furniture would look in a particular room. There are currently 15 Home Centre stores across the country in key cities including Gurgaon, Bangalore, Mumbai, Noida, Pune, Chennai, Delhi, Coimbatore, Mangalore and Hyderabad. Most of the stores are situated at high streets Malls and spread over a sprawling area of approx. 20,000 - 40,000 sq. ft. Home Centre features a host of products sourced from across the globe including furniture, home décor and soft furnishing, offering consumers a choice of categorized and coordinated shopping. The store’s USP is to provide a ‘touch and feel’ experience for shoppers and allows them to envisage how the products will lend a sense character and uniqueness to their home.        ",
        productList:"Furniture, homeware, soft furnishing, crockery, cutlery & kitchen utensils, bath products, wicker products, CD & magazine racks, towels, bed spreads, shower curtains, laundry hampers, utility brushes, iron boards, cutlery, glassware, lamps in sleek and tall patterns, artificial flowers, ceramic vases, crystal ware etc.",
        type : "Restaurant",
        location:"SG-23, Galleria Market, DLF City Phase IV, Gurugram, Haryana,122009",
        availability:"Open all day"
    },
    {
        key:3,
        name: "Yellow Door cafe",
        img:"./Assets/Images/Shop.jpg",
        city: "New Delhi",
        rating : 4.6,
        reviews : 21,
        contact : ["+(91)-9650560949", "(011)-9810962664"],
        email: "yellowdoorcafe@gmail.com",
        about:"Home Centre is a perfect destination to help you decorate your dream abode. Walk into our stores today to discover tasteful furniture, home ware and soft furnishing products that truly represents style, comfort and individuality. In the year 2005, Dubai based retail conglomerate Landmark Group launched its first specialized, stand-alone home improvement store – Home Centre. Home Centre is a one stop destination for furniture, homeware and soft furnishing that truly represents style, comfort and individuality. The stores use unique ‘concept’ rooms as the display model, to give consumers a practical idea of how each piece of furniture would look in a particular room. There are currently 15 Home Centre stores across the country in key cities including Gurgaon, Bangalore, Mumbai, Noida, Pune, Chennai, Delhi, Coimbatore, Mangalore and Hyderabad. Most of the stores are situated at high streets Malls and spread over a sprawling area of approx. 20,000 - 40,000 sq. ft. Home Centre features a host of products sourced from across the globe including furniture, home décor and soft furnishing, offering consumers a choice of categorized and coordinated shopping. The store’s USP is to provide a ‘touch and feel’ experience for shoppers and allows them to envisage how the products will lend a sense character and uniqueness to their home.        ",
        productList:"Furniture, homeware, soft furnishing, crockery, cutlery & kitchen utensils, bath products, wicker products, CD & magazine racks, towels, bed spreads, shower curtains, laundry hampers, utility brushes, iron boards, cutlery, glassware, lamps in sleek and tall patterns, artificial flowers, ceramic vases, crystal ware etc.",
        type : "Restaurant",
        location:"SG-23, Galleria Market, DLF City Phase IV, Gurugram, Haryana,122009",
        availability:"Open all day"
    },
    {
        key:4,
        name: "Yellow Door cafe",
        img:"./Assets/Images/Shop.jpg",
        city: "New Delhi",
        rating : 4.6,
        reviews : 21,
        contact : ["+(91)-9650560949", "(011)-9810962664"],
        email: "yellowdoorcafe@gmail.com",
        about:"Home Centre is a perfect destination to help you decorate your dream abode. Walk into our stores today to discover tasteful furniture, home ware and soft furnishing products that truly represents style, comfort and individuality. In the year 2005, Dubai based retail conglomerate Landmark Group launched its first specialized, stand-alone home improvement store – Home Centre. Home Centre is a one stop destination for furniture, homeware and soft furnishing that truly represents style, comfort and individuality. The stores use unique ‘concept’ rooms as the display model, to give consumers a practical idea of how each piece of furniture would look in a particular room. There are currently 15 Home Centre stores across the country in key cities including Gurgaon, Bangalore, Mumbai, Noida, Pune, Chennai, Delhi, Coimbatore, Mangalore and Hyderabad. Most of the stores are situated at high streets Malls and spread over a sprawling area of approx. 20,000 - 40,000 sq. ft. Home Centre features a host of products sourced from across the globe including furniture, home décor and soft furnishing, offering consumers a choice of categorized and coordinated shopping. The store’s USP is to provide a ‘touch and feel’ experience for shoppers and allows them to envisage how the products will lend a sense character and uniqueness to their home.        ",
        productList:"Furniture, homeware, soft furnishing, crockery, cutlery & kitchen utensils, bath products, wicker products, CD & magazine racks, towels, bed spreads, shower curtains, laundry hampers, utility brushes, iron boards, cutlery, glassware, lamps in sleek and tall patterns, artificial flowers, ceramic vases, crystal ware etc.",
        type : "Restaurant",
        location:"SG-23, Galleria Market, DLF City Phase IV, Gurugram, Haryana,122009",
        availability:"Open all day"
    },
    {
        key:5,
        name: "Yellow Door cafe",
        img:"./Assets/Images/Shop.jpg",
        city: "New Delhi",
        rating : 4.6,
        reviews : 21,
        contact : ["+(91)-9650560949", "(011)-9810962664"],
        email: "yellowdoorcafe@gmail.com",
        about:"Home Centre is a perfect destination to help you decorate your dream abode. Walk into our stores today to discover tasteful furniture, home ware and soft furnishing products that truly represents style, comfort and individuality. In the year 2005, Dubai based retail conglomerate Landmark Group launched its first specialized, stand-alone home improvement store – Home Centre. Home Centre is a one stop destination for furniture, homeware and soft furnishing that truly represents style, comfort and individuality. The stores use unique ‘concept’ rooms as the display model, to give consumers a practical idea of how each piece of furniture would look in a particular room. There are currently 15 Home Centre stores across the country in key cities including Gurgaon, Bangalore, Mumbai, Noida, Pune, Chennai, Delhi, Coimbatore, Mangalore and Hyderabad. Most of the stores are situated at high streets Malls and spread over a sprawling area of approx. 20,000 - 40,000 sq. ft. Home Centre features a host of products sourced from across the globe including furniture, home décor and soft furnishing, offering consumers a choice of categorized and coordinated shopping. The store’s USP is to provide a ‘touch and feel’ experience for shoppers and allows them to envisage how the products will lend a sense character and uniqueness to their home.        ",
        productList:"Furniture, homeware, soft furnishing, crockery, cutlery & kitchen utensils, bath products, wicker products, CD & magazine racks, towels, bed spreads, shower curtains, laundry hampers, utility brushes, iron boards, cutlery, glassware, lamps in sleek and tall patterns, artificial flowers, ceramic vases, crystal ware etc.",
        type : "Restaurant",
        location:"SG-23, Galleria Market, DLF City Phase IV, Gurugram, Haryana,122009",
        availability:"Open all day"
    },
    {
        key:6,
        name: "Yellow Door cafe",
        img:"./Assets/Images/Shop.jpg",
        city: "New Delhi",
        rating : 4.6,
        reviews : 21,
        contact : ["+(91)-9650560949", "(011)-9810962664"],
        email: "yellowdoorcafe@gmail.com",
        about:"Home Centre is a perfect destination to help you decorate your dream abode. Walk into our stores today to discover tasteful furniture, home ware and soft furnishing products that truly represents style, comfort and individuality. In the year 2005, Dubai based retail conglomerate Landmark Group launched its first specialized, stand-alone home improvement store – Home Centre. Home Centre is a one stop destination for furniture, homeware and soft furnishing that truly represents style, comfort and individuality. The stores use unique ‘concept’ rooms as the display model, to give consumers a practical idea of how each piece of furniture would look in a particular room. There are currently 15 Home Centre stores across the country in key cities including Gurgaon, Bangalore, Mumbai, Noida, Pune, Chennai, Delhi, Coimbatore, Mangalore and Hyderabad. Most of the stores are situated at high streets Malls and spread over a sprawling area of approx. 20,000 - 40,000 sq. ft. Home Centre features a host of products sourced from across the globe including furniture, home décor and soft furnishing, offering consumers a choice of categorized and coordinated shopping. The store’s USP is to provide a ‘touch and feel’ experience for shoppers and allows them to envisage how the products will lend a sense character and uniqueness to their home.        ",
        productList:"Furniture, homeware, soft furnishing, crockery, cutlery & kitchen utensils, bath products, wicker products, CD & magazine racks, towels, bed spreads, shower curtains, laundry hampers, utility brushes, iron boards, cutlery, glassware, lamps in sleek and tall patterns, artificial flowers, ceramic vases, crystal ware etc.",
        type : "Restaurant",
        location:"SG-23, Galleria Market, DLF City Phase IV, Gurugram, Haryana,122009",
        availability:"Open all days"
    },
    {
        key:7,
        name: "Yellow Door cafe",
        img:"./Assets/Images/Shop.jpg",
        city: "New Delhi",
        rating : 4.6,
        reviews : 21,
        contact : ["+(91)-9650560949", "(011)-9810962664"],
        email: "yellowdoorcafe@gmail.com",
        about:"Home Centre is a perfect destination to help you decorate your dream abode. Walk into our stores today to discover tasteful furniture, home ware and soft furnishing products that truly represents style, comfort and individuality. In the year 2005, Dubai based retail conglomerate Landmark Group launched its first specialized, stand-alone home improvement store – Home Centre. Home Centre is a one stop destination for furniture, homeware and soft furnishing that truly represents style, comfort and individuality. The stores use unique ‘concept’ rooms as the display model, to give consumers a practical idea of how each piece of furniture would look in a particular room. There are currently 15 Home Centre stores across the country in key cities including Gurgaon, Bangalore, Mumbai, Noida, Pune, Chennai, Delhi, Coimbatore, Mangalore and Hyderabad. Most of the stores are situated at high streets Malls and spread over a sprawling area of approx. 20,000 - 40,000 sq. ft. Home Centre features a host of products sourced from across the globe including furniture, home décor and soft furnishing, offering consumers a choice of categorized and coordinated shopping. The store’s USP is to provide a ‘touch and feel’ experience for shoppers and allows them to envisage how the products will lend a sense character and uniqueness to their home.        ",
        productList:"Furniture, homeware, soft furnishing, crockery, cutlery & kitchen utensils, bath products, wicker products, CD & magazine racks, towels, bed spreads, shower curtains, laundry hampers, utility brushes, iron boards, cutlery, glassware, lamps in sleek and tall patterns, artificial flowers, ceramic vases, crystal ware etc.",
        type : "Restaurant",
        location:"SG-23, Galleria Market, DLF City Phase IV, Gurugram, Haryana,122009",
        availability:"Open all days"
    },
    {
        key:8,
        name: "Yellow Door cafe",
        img:"./Assets/Images/Shop.jpg",
        city: "New Delhi",
        rating : 4.6,
        reviews : 21,
        contact : ["+(91)-9650560949", "(011)-9810962664"],
        email: "yellowdoorcafe@gmail.com",
        about:"Home Centre is a perfect destination to help you decorate your dream abode. Walk into our stores today to discover tasteful furniture, home ware and soft furnishing products that truly represents style, comfort and individuality. In the year 2005, Dubai based retail conglomerate Landmark Group launched its first specialized, stand-alone home improvement store – Home Centre. Home Centre is a one stop destination for furniture, homeware and soft furnishing that truly represents style, comfort and individuality. The stores use unique ‘concept’ rooms as the display model, to give consumers a practical idea of how each piece of furniture would look in a particular room. There are currently 15 Home Centre stores across the country in key cities including Gurgaon, Bangalore, Mumbai, Noida, Pune, Chennai, Delhi, Coimbatore, Mangalore and Hyderabad. Most of the stores are situated at high streets Malls and spread over a sprawling area of approx. 20,000 - 40,000 sq. ft. Home Centre features a host of products sourced from across the globe including furniture, home décor and soft furnishing, offering consumers a choice of categorized and coordinated shopping. The store’s USP is to provide a ‘touch and feel’ experience for shoppers and allows them to envisage how the products will lend a sense character and uniqueness to their home.        ",
        productList:"Furniture, homeware, soft furnishing, crockery, cutlery & kitchen utensils, bath products, wicker products, CD & magazine racks, towels, bed spreads, shower curtains, laundry hampers, utility brushes, iron boards, cutlery, glassware, lamps in sleek and tall patterns, artificial flowers, ceramic vases, crystal ware etc.",
        type : "Restaurant",
        location:"SG-23, Galleria Market, DLF City Phase IV, Gurugram, Haryana,122009",
        availability:"Open all days"
    },
    {
        key:9,
        name: "Yellow Door cafe",
        img:"./Assets/Images/Shop.jpg",
        city: "New Delhi",
        rating : 4.6,
        reviews : 21,
        contact : ["+(91)-9650560949", "(011)-9810962664"],
        email: "yellowdoorcafe@gmail.com",
        about:"Home Centre is a perfect destination to help you decorate your dream abode. Walk into our stores today to discover tasteful furniture, home ware and soft furnishing products that truly represents style, comfort and individuality. In the year 2005, Dubai based retail conglomerate Landmark Group launched its first specialized, stand-alone home improvement store – Home Centre. Home Centre is a one stop destination for furniture, homeware and soft furnishing that truly represents style, comfort and individuality. The stores use unique ‘concept’ rooms as the display model, to give consumers a practical idea of how each piece of furniture would look in a particular room. There are currently 15 Home Centre stores across the country in key cities including Gurgaon, Bangalore, Mumbai, Noida, Pune, Chennai, Delhi, Coimbatore, Mangalore and Hyderabad. Most of the stores are situated at high streets Malls and spread over a sprawling area of approx. 20,000 - 40,000 sq. ft. Home Centre features a host of products sourced from across the globe including furniture, home décor and soft furnishing, offering consumers a choice of categorized and coordinated shopping. The store’s USP is to provide a ‘touch and feel’ experience for shoppers and allows them to envisage how the products will lend a sense character and uniqueness to their home.        ",
        productList:"Furniture, homeware, soft furnishing, crockery, cutlery & kitchen utensils, bath products, wicker products, CD & magazine racks, towels, bed spreads, shower curtains, laundry hampers, utility brushes, iron boards, cutlery, glassware, lamps in sleek and tall patterns, artificial flowers, ceramic vases, crystal ware etc.",
        type : "Restaurant",
        location:"SG-23, Galleria Market, DLF City Phase IV, Gurugram, Haryana,122009",
        availability:"Open all days"
    },
];  