module.exports = [
    {
        key: 1,
        imgurl: '../../Images/SingleBlogBanner.png',
        blogTitle: 'ROAD TRIP',
        date: '16 Dec 2022',
        blogTitle2: 'Lorem Ipsum Topic',
        username: 'Pradeep Vishawakarma',
        user_img_url: '../../Images/UserImg.png',
        likes: '12',
        text: ' Lorem ipsum dolor sit, amet consectetur adipisicing elit. Molestias, officia voluptatem perspiciatis, porro saepe ipsa quam excepturi similique iusto sint officiis. Quae corrupti, consectetur ex minus eveniet esse tempore odit.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Molestias, officia voluptatem perspiciatis, porro saepe ipsa quam excepturi similique iusto sint officiis. Quae corrupti, consectetur ex minus eveniet esse tempore odit.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Molestias, officia voluptatem perspiciatis, porro saepe ipsa quam excepturi similique iusto sint officiis. Quae corrupti, consectetur ex minus eveniet esse tempore odit.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Molestias, officia voluptatem perspiciatis, porro saepe ipsa quam excepturi similique iusto sint officiis. Quae corrupti, consectetur ex minus eveniet esse tempore odit.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Molestias, officia voluptatem perspiciatis, porro saepe ipsa quam excepturi similique iusto sint officiis. Quae corrupti, consectetur ex minus eveniet esse tempore odit.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Molestias, officia voluptatem perspiciatis, porro saepe ipsa quam excepturi similique iusto sint officiis. Quae corrupti, consectetur ex minus eveniet esse tempore odit.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Molestias, officia voluptatem perspiciatis, porro saepe ipsa quam excepturi similique iusto sint officiis. Quae corrupti, consectetur ex minus eveniet esse tempore odit.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Molestias, officia voluptatem perspiciatis, porro saepe ipsa quam excepturi similique iusto sint officiis. Quae corrupti, consectetur ex minus eveniet esse tempore odit.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Molestias, officia voluptatem perspiciatis, porro saepe ipsa quam excepturi similique iusto sint officiis. Quae corrupti, consectetur ex minus eveniet esse tempore odit.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Molestias, officia voluptatem perspiciatis, porro saepe ipsa quam excepturi similique iusto sint officiis. Quae corrupti, consectetur ex minus eveniet esse tempore odit.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Molestias, officia voluptatem perspiciatis, porro saepe ipsa quam excepturi similique iusto sint officiis. Quae corrupti, consectetur ex minus eveniet esse tempore odit.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Molestias, officia voluptatem perspiciatis, porro saepe ipsa quam excepturi similique iusto sint officiis. Quae corrupti, consectetur ex minus eveniet esse tempore odit. '

    }
]