module.exports = [
  {
    key: 1,
    name: "Ambience Mall Vasant Kunj",
    img: "./Assets/Images/TrendingBusiness.jpg",
    city: "New Delhi",
    rating: 4.6,
    reviews: 21,
    desc: "Ambience Mall, Vasant Kunj is an apogee of lifestyle distinction. We offer an experience of unparalleled retail mix combined with entertainment and leisure attractions that has changed the concept of shopping mall experience.",
    category:
      "Ambience Mall is popular not just for its shopping, but also its wide array of entertainment options.",
    availability: "Open All Days",
  },
  {
    key: 2,
    name: "Chandni Chowk",
    img: "./Assets/Images/TrendingBusiness.jpg",
    city: "New Delhi",
    rating: 4.6,
    reviews: 21,
    desc: "It is the perfect place to shop in. This densely populated market has been around for more than three centuries and was once visited by merchants from Turkey, China and even Holland. You may buy curios and souvenirs from here.",
    category:
      "Clothing, Footwear, Optician, Jewellery, Books & Toys, Beauty, Stationery / Art",
    availability: "Sunday Closed",
  },
  {
    key: 3,
    name: "Ambience Mall Vasant Kunj",
    img: "./Assets/Images/TrendingBusiness.jpg",
    city: "New Delhi",
    rating: 4.6,
    reviews: 21,
    desc: "Ambience Mall, Vasant Kunj is an apogee of lifestyle distinction. We offer an experience of unparalleled retail mix combined with entertainment and leisure attractions that has changed the concept of shopping mall experience.",
    category:
      "Ambience Mall is popular not just for its shopping, but also its wide array of entertainment options.",
    availability: "Open All Days",
  },
  {
    key: 4,
    name: "Chandni Chowk",
    img: "./Assets/Images/TrendingBusiness.jpg",
    city: "New Delhi",
    rating: 4.6,
    reviews: 21,
    desc: "It is the perfect place to shop in. This densely populated market has been around for more than three centuries and was once visited by merchants from Turkey, China and even Holland. You may buy curios and souvenirs from here.",
    category:
      "Clothing, Footwear, Optician, Jewellery, Books & Toys, Beauty, Stationery / Art",
    availability: "Sunday Closed",
  },
  {
    key: 5,
    name: "Ambience Mall Vasant Kunj",
    img: "./Assets/Images/TrendingBusiness.jpg",
    city: "New Delhi",
    rating: 4.6,
    reviews: 21,
    desc: "Ambience Mall, Vasant Kunj is an apogee of lifestyle distinction. We offer an experience of unparalleled retail mix combined with entertainment and leisure attractions that has changed the concept of shopping mall experience.",
    category:
      "Ambience Mall is popular not just for its shopping, but also its wide array of entertainment options.",
    availability: "Open All Days",
  },
  {
    key: 6,
    name: "Chandni Chowk",
    img: "./Assets/Images/TrendingBusiness.jpg",
    city: "New Delhi",
    rating: 4.6,
    reviews: 21,
    desc: "It is the perfect place to shop in. This densely populated market has been around for more than three centuries and was once visited by merchants from Turkey, China and even Holland. You may buy curios and souvenirs from here.",
    category:
      "Clothing, Footwear, Optician, Jewellery, Books & Toys, Beauty, Stationery / Art",
    availability: "Sunday Closed",
  },
  {
    key: 7,
    name: "Ambience Mall Vasant Kunj",
    img: "./Assets/Images/TrendingBusiness.jpg",
    city: "New Delhi",
    rating: 4.6,
    reviews: 21,
    desc: "Ambience Mall, Vasant Kunj is an apogee of lifestyle distinction. We offer an experience of unparalleled retail mix combined with entertainment and leisure attractions that has changed the concept of shopping mall experience.",
    category:
      "Ambience Mall is popular not just for its shopping, but also its wide array of entertainment options.",
    availability: "Open All Days",
  },
  {
    key: 8,
    name: "Chandni Chowk",
    img: "./Assets/Images/TrendingBusiness.jpg",
    city: "New Delhi",
    rating: 4.6,
    reviews: 21,
    desc: "It is the perfect place to shop in. This densely populated market has been around for more than three centuries and was once visited by merchants from Turkey, China and even Holland. You may buy curios and souvenirs from here.",
    category:
      "Clothing, Footwear, Optician, Jewellery, Books & Toys, Beauty, Stationery / Art",
    availability: "Sunday Closed",
  },
  {
    key: 9,
    name: "Ambience Mall Vasant Kunj",
    img: "./Assets/Images/TrendingBusiness.jpg",
    city: "New Delhi",
    rating: 4.6,
    reviews: 21,
    desc: "Ambience Mall, Vasant Kunj is an apogee of lifestyle distinction. We offer an experience of unparalleled retail mix combined with entertainment and leisure attractions that has changed the concept of shopping mall experience.",
    category:
      "Ambience Mall is popular not just for its shopping, but also its wide array of entertainment options.",
    availability: "Open All Days",
  },
  {
    key: 10,
    name: "Chandni Chowk",
    img: "./Assets/Images/TrendingBusiness.jpg",
    city: "New Delhi",
    rating: 4.6,
    reviews: 21,
    desc: "It is the perfect place to shop in. This densely populated market has been around for more than three centuries and was once visited by merchants from Turkey, China and even Holland. You may buy curios and souvenirs from here.",
    category:
      "Clothing, Footwear, Optician, Jewellery, Books & Toys, Beauty, Stationery / Art",
    availability: "Sunday Closed",
  },
  {
    key: 11,
    name: "Ambience Mall Vasant Kunj",
    img: "./Assets/Images/TrendingBusiness.jpg",
    city: "New Delhi",
    rating: 4.6,
    reviews: 21,
    desc: "Ambience Mall, Vasant Kunj is an apogee of lifestyle distinction. We offer an experience of unparalleled retail mix combined with entertainment and leisure attractions that has changed the concept of shopping mall experience.",
    category:
      "Ambience Mall is popular not just for its shopping, but also its wide array of entertainment options.",
    availability: "Open All Days",
  },
  {
    key: 12,
    name: "Chandni Chowk",
    img: "./Assets/Images/TrendingBusiness.jpg",
    city: "New Delhi",
    rating: 4.6,
    reviews: 21,
    desc: "It is the perfect place to shop in. This densely populated market has been around for more than three centuries and was once visited by merchants from Turkey, China and even Holland. You may buy curios and souvenirs from here.",
    category:
      "Clothing, Footwear, Optician, Jewellery, Books & Toys, Beauty, Stationery / Art",
    availability: "Sunday Closed",
  },
  {
    key: 13,
    name: "Chandni Chowk",
    img: "./Assets/Images/TrendingBusiness.jpg",
    city: "New Delhi",
    rating: 4.6,
    reviews: 21,
    desc: "It is the perfect place to shop in. This densely populated market has been around for more than three centuries and was once visited by merchants from Turkey, China and even Holland. You may buy curios and souvenirs from here.",
    category:
      "Clothing, Footwear, Optician, Jewellery, Books & Toys, Beauty, Stationery / Art",
    availability: "Sunday Closed",
  },
  {
    key: 13,
    name: "Chandni Chowk",
    img: "./Assets/Images/TrendingBusiness.jpg",
    city: "New Delhi",
    rating: 4.6,
    reviews: 21,
    desc: "It is the perfect place to shop in. This densely populated market has been around for more than three centuries and was once visited by merchants from Turkey, China and even Holland. You may buy curios and souvenirs from here.",
    category:
      "Clothing, Footwear, Optician, Jewellery, Books & Toys, Beauty, Stationery / Art",
    availability: "Sunday Closed",
  },
];
